version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: elasticsearch
    network_mode: bridge
    environment:
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS:--Xms512m -Xmx512m}"
    volumes:
      - ${ELASTICSEARCH_DATA}:/usr/share/elasticsearch/data
    ports:
      - 9400:9200
    restart: always
  
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.2
    network_mode: bridge
    container_name: logstash
    external_links:
      - elasticsearch:elasticsearch
    volumes:
      - ./logstash/pipeline/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
      - http.host=0.0.0.0
      - path.config=/usr/share/logstash/pipeline
    links:
      - elasticsearch
    restart: always
  
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.2
    network_mode: bridge
    container_name: kibana-6.1.2
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    restart: always
    
volumes:
  esdata1:
    driver: local