version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # volumes:
      # - esdata1:/storage/docker/elasticsearch-datadir/data
    ports:
      - 9400:9200
    networks:
      - elk
    restart: always
  
  logstash:
    image: docker.elastic.co/logstash/logstash:6.1.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always
  
#  kibana:
#    image: docker.elastic.co/kibana/kibana:6.1.2
#    volumes:
#      - ./kibana/config/:/usr/share/kibana/config:ro
#    ports:
#      - "5601:5601"
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch
#    restart: always
    
volumes:
  esdata1:
    driver: local

networks:
  elk:
    driver: bridge