version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # volumes:
      # - esdata1:/storage/docker/elasticsearch-datadir/data
    ports:
      - 9400:9200
    networks:
      - elk
    restart: always
  
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.2
    volumes:
      - ./logstash/pipeline/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
#      - xpack.security.enabled=false
#      - xpack.monitoring.enabled=false
#      - xpack.ml.enabled=false
#      - xpack.graph.enabled=false
#      - xpack.watcher.enabled=false
#      - xpack.monitoring.elasticsearch.url=http://elasticsearch:9200
#      - xpack.monitoring.elasticsearch.username=logstash_system
#      - xpack.monitoring.elasticsearch.password=changeme
#      - xpack.monitoring.enabled=false
      - http.host=0.0.0.0
      - path.config=/usr/share/logstash/pipeline
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always
  
#  kibana:
#    image: docker.elastic.co/kibana/kibana:6.1.2
#    volumes:
#      - ./kibana/config/:/usr/share/kibana/config:ro
#    ports:
#      - "5601:5601"
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch
#    restart: always
    
volumes:
  esdata1:
    driver: local

networks:
  elk:
    driver: bridge